CREATE TABLE livros (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) DEFAULT NULL,
    name VARCHAR(255) DEFAULT NULL,
    nationality VARCHAR(255) DEFAULT NULL,
    isbn VARCHAR(255) DEFAULT NULL,
    year INT DEFAULT NULL,
    location VARCHAR(255) DEFAULT NULL,
    category TINYINT DEFAULT NULL,
    language VARCHAR(255) DEFAULT NULL
);
